apiVersion: v2
name: vitistack-operator
description: A Helm chart for the Vitistack Operator
type: application
version: 0.1.0
appVersion: "1.16.0"
annotations:
  "artifacthub.io/crds": |
    - kind: Vitistack
      name: vitistacks.vitistack.io
      version: v1alpha1
    - kind: KubernetesProvider
      name: kubernetesproviders.vitistack.io
      version: v1alpha1
    - kind: MachineProvider
      name: machineproviders.vitistack.io
      version: v1alpha1

# Chart icon - displayed in Helm repository UIs like ArtifactHub
icon: https://vitistack.io/images/viti1.svg
